### ISSUE TITLE
Get customer family from customer ID in PHP

### ISSUE THREAD

**Issue by abraham63** [thelia-modules/CustomerFamily#11]
Hi and thanks for this module.

How can I get the customer family of a customer in PHP.
I need it in a controller do to specific stuff depending of the family.
I get the ID but I don't know how I can get the family of this customer.

Thanks for help

**Comment by etiennePerriere** [comment]
Hi, since there is a `customer_customer_family` table and a `CustomerCustomerFamily` model, I guess you can use it to retrieve Customer <=> Family in both ways with an ID ?
